### ISSUE TITLE
[Enhancement Request] Enhance Sedna federated learning CRD and LIB interface.

### ISSUE THREAD

**Issue by jaypume** [kubeedge/sedna#161]
**What would you like to be added/modified**:

- Support edge workers and cloud workers being started on demand to avoid GPU resource occupation.
- Support aggregation trigger, stop condition, client choose algorithm being configured through CRD.
- Add transmission interface to decouple transmission implementations, to support s3 and websocket protocal.
- Extend the aggregation interface to support representation extraction aggregation algorithm such as MistNet.

**Why is this needed**:
- Reducing GPU resources frees up more resources and **reduces costs**.
- Configuring aggregation jobs through CRD provides more **flexible** functions for deployers.
- Abstracting transmission interface can *shield* the different edge cloud network environments.
- Extending the aggregation interface enable more aggregation algorithm to be integrated to Sedna.

**Comment by jaypume** [comment]
The following is proposed CRD, and it also already discussed before in issue #50 :
```yaml
apiVersion: sedna.io/v1alpha1
kind: FederatedLearningJob
metadata:
  name: surface-defect-detection
spec:
  stopCondition:
    operator: "or" # and
      conditions:
        - operator: ">="
          threshold: 100
          metric: rounds
        - operator: ">"
          threshold: 0.95
          metric: target_accuracy
        - operator: "<"
          threshold: 0.03
          metric: delta_loss
  transimitter:
    transimitterAlgorithms:
      - name: "simple" # simple, adaptive_freezing, adaptive_sync ...
  aggregationTrigger:
    condition:
      operator: ">"
      threshold: 5
      metric: num_of_select_clients
  aggregationWorker:
    model:
      name: "surface-defect-detection-model"
    template:
      spec:
        nodeName: "cloud"
        containers:
          - image: kubeedge/sedna-example-federated-learning-surface-defect-detection-aggregation:v0.1.0
            name: agg-worker
            imagePullPolicy: IfNotPresent
            env: # user defined environments
              - name: "cut_layer"
                value: "4"
              - name: "epsilon"
                value: "100"
              - name: "aggregation_algorithm"
                value: "mistnet"
              - name: "batch_size"
                value: "32"
            resources: # user defined resources
              limits:
                memory: 2Gi
  trainingWorkers:
    - dataset:
        name: "edge1-surface-defect-detection-dataset"
      template:
        spec:
          nodeName: "edge1"
          containers:
            - image: kubeedge/sedna-example-federated-learning-surface-defect-detection-train:v0.1.0
              name: train-worker
              imagePullPolicy: IfNotPresent
              env: # user defined environments
                - name: "batch_size"
                  value: "32"
                - name: "learning_rate"
                  value: "0.001"
                - name: "epochs"
                  value: "1"
              resources: # user defined resources
                limits:
                  memory: 2Gi
    - dataset:
        name: "edge2-surface-defect-detection-dataset"
      template:
        spec:
          nodeName: "edge2"
          containers:
            - image: kubeedge/sedna-example-federated-learning-surface-defect-detection-train:v0.1.0
              name: train-worker
              imagePullPolicy: IfNotPresent
              env: # user defined environments
                - name: "batch_size"
                  value: "32"
                - name: "learning_rate"
                  value: "0.001"
                - name: "epochs"
                  value: "1"
              resources: # user defined resources
                limits:
                  memory: 2Gi
```

**Comment by jaypume** [comment]
The following is proposed Lib interface, more detailed code can be found in PR:
**aggregate.py:**
``` python
def run_server():
    server = AggregationServer(
        data = data, 
        estimator=estimator, 
        aggregation=aggregation, 
        transmitter=transmitter, 
        chooser=chooser)
    
    server.start()

if __name__ == '__main__':
    run_server()
```

**train.py:**
```python
def train():
    
    fl_model = FederatedLearning(
        data=data, 
        estimator=estimator, 
        aggregation=aggregation, 
        transmitter=transmitter)

    fl_model.train()

if __name__ == '__main__':
    train()
```

**Comment by jaypume** [comment]
### Overall Sequence Diagram
![design](http://www.plantuml.com/plantuml/png/ZLNVRzjK57xtNt5L90hIHgahNY90axp2Iz2GDYalbP1htxfNSsph-cQiRyawIiU2MY1Zh6JhWhfIJQnf4NHR5x9_9lV6UUg_mEVu9d8QcFRWoFUSxtpdo_bnVIaMDXULic_CnbG85dXn0Q_NMH3Pt2uJdwrGdmNqgk2seDuQYKEVkOOnAvZmAL7t7_U_Er7LMj8waDsQkdUalZzCQet1hNtvRB_tyh5Hjbcm0YPAa4bGmtP4o8bB8pzSevpOCRcy-AM1P88vBB83GJx_0bRyJXXdYjPIuFXXnPr9lKNBcdHRgMifA8NyEkKp9CLO9VAEpxnLiUnNw3GPTJsgkHOdlOlmZAZcXv35qlp_SkNHfaQRURHh2tlPZYcvkc2WSFAtHuDljxBgz5uyArgojjCxtP0_FUsT_jexlQlMlpdhx1gpvDgLorSA95v83hl9OUkiKq-UjsNtDZnVsy9P9QfvAZTFG0dIebKWyqHmvdcK6wWekVWfyXL8L14auXJTGnDTKWvTwXCHagKWNYZCpKMsM9qBL-Q6zW-YPHsAwXU8moaQzjLdnVS05c5aXO7B10k32uYsFOzJpqwFrxAixnje74BH6gXU2no2neS6ZbfB9jlGCAi4L3fxPDYwh7xfTB0Ro0gtOPKq3aHCa7U9upEAYZkhOHZJ0aIafTTjkf0_cLciba9zweXpQ389Tsa-iTQC8cY9RmgU7_qXpCW8dlUEYU4ty92FBmwBWUBgTgJMCS4AQbxXbD2RWYDqv4iZAbWPn8mGwLZbX2Cy9yMSbcBcfPW6dl-KOeu9fgMORot5n4oICej5G8NwiwMQTzJFHzdjW47MZBqNLVL7InuT9wqwh8YG-xVKesQ6mvAeTYFfhikzt_ixjvFsGs3wnwzwdOuwQAcxksD614wC1j3zxOr-u_YiipFcadjFGNGUgdvfowqV-erTsJpWOILmPQSgz_u2JDNl39fL-MDzSE-rkd-IlDxEL0xM_u4zsQ-fHblLQq2kXNvuuoFry8dSU41lskN8fx2c6-ECDWOqMJukjzgzLq_azgPyUPBy_HnHuDI-Jpw4SkIIrGSeIafmdaSrkdBpo7VIPBMTqKsGNH1wRFNKwwk0vFPK0zvozVApaUypVDDpazlLV49OHwlFcQ0QUsxPC2d3gSNB9HguwQV8-1S0)


###  AggregationTrigger Design

### PlatoConfig

### Representation Data Storage

**Comment by jaypume** [comment]
###  AggregationTrigger Design

**Comment by jaypume** [comment]
### PlatoConfig

**Comment by jaypume** [comment]
### Representation Data Storage

**Comment by jaypume** [comment]
refer to https://github.com/kubeedge/sedna/issues/161#issuecomment-899973858

The following is corresponding environment variables passed to container:
```
TRANSMITTER: s3/ws
TRANSMITTER_S3_PARAM: {"aggDataPath": "s3://sedna/fl/aggregation_data", "credentialName": "mysecret"}
```

**Comment by JimmyYang20** [comment]
```yaml
transimitter: # option
    ws: { } # option, by default
    s3: # option, but at least one
      aggDataPath: "s3://sedna/fl/aggregation_data"
      credentialName: mysecret
```
@jaypume @llhuii 
1. transimitter => transmitter ?
2. if ws is the default transmitter, why does the user still need to write it in the CRD. suggest to delete.
