### ISSUE TITLE
Add shared storage support for dataset/model

### ISSUE THREAD

**Issue by llhuii** [kubeedge/sedna#18]
#### What would you like to be added:
Add shared storage support for dataset/model, such as s3/http protocols.
#### Why is this needed:
Currently only dataset/model uri with **host** localpath is supported, thus limiting cross node model training/serving.

**Comment by llhuii** [comment]
## sub-problem 1: model/dataset download
There are three solutions:
### solution 1: Add init container+emptydir to download model/dataset for worker-Pod
pros:
1. auto manage for model/dataset cached directory(k8s emptydir)
1. no extra manage for this init container(attached to worker Pod)
1. decouple/independent with the worker image, no need to extra download for worker
1. leverage existing train/serving images which only support localpath
1. can leverage existing image for this init-container, e.g. [kf serving storage-initialize](https://github.com/kubeflow/kfserving/blob/master/python/storage-initializer.Dockerfile)

cons:
1. only download dataset/model before worker running, not in the middle of worker.
1. can't share already downloaded model between workers.

**Comment by llhuii** [comment]
solution 2: Add extra pod to download model/dataset before running the worker Pod
pros:
1. can share already downloaded model between worker Pods.
cons:
1. complex manage/implement: need to manage this extra pod and running successfully prior to running the worker
2. extra manage for local download path

**Comment by llhuii** [comment]
### solution 3: let worker Pod downloads model/dataset by themselves before training or serving model
pros:
1. simple, no modify for our framework

cons:
1. need to change the worker image to do the downloading work
2. coupled with existing worker-images if we want to leverage them

**Comment by llhuii** [comment]
## sub-problem 2: model/dataset upload

Since the upload action is triggered by worker, we leave the uploading to the worker.
Specifically the worker can call:
1. minio/s3 client if modeluri is s3
2. http client if http
3. os.write files by attaching PV volumes or hostpath if local.

**Comment by TymonXie** [comment]
![image](https://user-images.githubusercontent.com/30067438/111561087-dc104a80-87ce-11eb-93c9-22e83d0576e6.png)

**Comment by llhuii** [comment]
More comment: we can use the kfserving init-container image(gcr.io/kfserving/storage-initializer:v0.4.1) for our init-container image.

**Comment by llhuii** [comment]
For dataset in s3:
In incremental learning feature, LocalController will split the dataset into train/test set, and upload to s3, then we need user to config s3 secrets.

**Comment by JimmyYang20** [comment]
### Create s3 Secret
Use s3 user credential to create a secret,   GM reads the secret annotations to inject the s3 environment variables to workers and LC.

```
apiVersion: v1
kind: Secret
metadata:
  name: secret-sedna
  annotations:
     sedna.io/s3-endpoint: s3.amazonaws.com # replace with your s3 endpoint
     sedna.io/s3-usehttps: "1" # by default 1
     sedna.io/s3-region: "cn-north-1" # replace with the region the bucket is created in
type: Opaque
data:
  AWS_ACCESS_KEY_ID: bWluaW8= # replace with your base64 encoded s3 credential
  AWS_SECRET_ACCESS_KEY: bWluaW8xMjM= # replace with your base64 encoded s3 credential
```

**Comment by llhuii** [comment]
/cc @EnfangCui

note: https://github.com/kubeedge/sedna/issues/16 also has the same secret design issue.

**Comment by JimmyYang20** [comment]
**KFServing uses s3**

create secret
```
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
  annotations:
     serving.kubeflow.org/s3-endpoint: s3.amazonaws.com # replace with your s3 endpoint
     serving.kubeflow.org/s3-usehttps: "1" # by default 1, for testing with minio you need to set to 0
     serving.kubeflow.org/s3-region: "us-east-2" # replace with the region the bucket is created in
type: Opaque
data:
  AWS_ACCESS_KEY_ID: bWluaW8= # replace with your base64 encoded s3 credential
  AWS_SECRET_ACCESS_KEY: bWluaW8xMjM= # replace with your base64 encoded s3 credential
```
attach the secret to the service account's secret list
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa
secrets:
- name: mysecret
```
create the inferenceservice
```
apiVersion: "serving.kubeflow.org/v1beta1"
kind: "InferenceService"
metadata:
  name: "mnist-s3"
spec:
  predictor:
    serviceAccountName: sa
    tensorflow:
      storageUri: "s3://kfserving-examples/mnist"
```
reference: [https://github.com/kubeflow/kfserving/tree/master/docs/samples/storage/s3](https://github.com/kubeflow/kfserving/tree/master/docs/samples/storage/s3)

kfserving python sdk gives set_credentials api
```python
from kfserving import KFServingClient

KFServing = KFServingClient()
KFServing.set_credentials(storage_type='S3',
                          namespace='kubeflow',
                          credentials_file='/tmp/awcredentials',
                          s3_profile='default',
                          s3_endpoint='s3.us-west-amazonaws.com',
                          s3_region='us-west-2',
                          s3_use_https='1',
                          s3_verify_ssl='0')
```
set credentials in the AWS credentials profile file on your local system, located at:
```~/.aws/credentials on Linux, macOS, or Unix```
this file should contain lines in the following format:
```
[default]
aws_access_key_id = your_access_key_id
aws_secret_access_key = your_secret_access_key
```
reference: 
[kfserving python adk gives set_credentials](https://github.com/kubeflow/kfserving/blob/master/python/kfserving/docs/KFServingClient.md#set_credentials)
[set aws credentials](https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/setup-credentials.html)

**Sedon-Core uses s3**
create secret
```
apiVersion: v1
kind: Secret
metadata:
  name: seldon-init-container-secret
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: minioadmin
  AWS_SECRET_ACCESS_KEY: minioadmin
  AWS_ENDPOINT_URL: http://minio.minio-system.svc.cluster.local:9000
  USE_SSL: "false"
```

init contrainer:
```
initContainers:
        - name: classifier-model-initializer
          image: gcr.io/kfserving/storage-initializer:v0.4.0
          imagePullPolicy: IfNotPresent
          args:
          - s3://sklearn/iris
          - /mnt/models

          envFrom:
          - secretRef:
              name: seldon-init-container-secret
```

create a deployment
```
apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: rclone-sklearn
spec:
  predictors:
  - name: default
    replicas: 1
    graph:
      name: classifier
      implementation: SKLEARN_SERVER
      modelUri: mys3:sklearn/iris
      storageInitializerImage: gcr.io/kfserving/storage-initializer:v0.4.0    # Specify custom image here
      envSecretRefName: seldon-init-container-secret                          # Specify custom secret here
```
envSecretRefName:
```go
// Inject credentials using secretRef
	if envSecretRefName != "" {
		initContainer.EnvFrom = append(initContainer.EnvFrom,
			corev1.EnvFromSource{
				SecretRef: &corev1.SecretEnvSource{
					LocalObjectReference: corev1.LocalObjectReference{
						Name: envSecretRefName,
					},
				},
			})
	}
```
reference:
[seldon-core minio secret](https://github.com/SeldonIO/seldon-core/blob/master/examples/minio/secret.yaml)
[seldon-core init containers](https://github.com/SeldonIO/seldon-core/blob/228b41765fc57fda26f0b5d00526ff423d06206d/doc/source/servers/overview.md#init-containers)
