### ISSUE TITLE
Add pod template like support for worker spec

### ISSUE THREAD

**Issue by llhuii** [kubeedge/sedna#19]
#### What would you like to be added:
Add pod template like support for worker spec
#### Why is this needed:
Current state of the worker spec definition:
```go
 type WorkerSpec struct {
    ScriptDir        string     `json:"scriptDir"`
    ScriptBootFile   string     `json:"scriptBootFile"`
    FrameworkType    string     `json:"frameworkType"`
    FrameworkVersion string     `json:"frameworkVersion"`
    Parameters       []ParaSpec `json:"parameters"`
 }

 // ParaSpec is a description of a parameter
 type ParaSpec struct {
    Key   string `json:"key"`
    Value string `json:"value"`
 }
```

1. `ScriptDir/ScriptBootFile` is the entrypoint of worker, localpath or shared storage(e.g. s3).
1. `FrameworkType/FrameworkVersion` specifies the base container image of worker.
1. `Parameters` specifies the environment of worker.

pros:
1. simply for demo

cons:
1. need to copy the code script to all known nodes manually.
1. don't support docker-container cap: code version mgmt, distribution etc.
1. don't support k8s pod similar features: resource limits, user defined volumes etc.
1. need shared storage(e.g. s3) for code if not localpath.
1. need to build base image if the current base image can't satisfy the user
requirements(user-defined code package dependents, or new framework).
And then reedit the configuration of GM and restart it.

**Comment by llhuii** [comment]
So we need to add pod template support to avoid the cons of current worker spec.

changes:
1. refactor workerSpec of API/implementation to pod template
2. change CRD of all features, and we can avoid this by kube-builder #11 
3. move nodeName of API to pod template
4. update all three examples
5. update the installation doc
6. update the local-up script

And here are examples:
#### joint-inference-service CR example
so the example of joint-inference [in here](https://github.com/kubeedge/sedna/blob/main/build/crd-samples/sedna/jointinferenceservice_v1alpha1.yaml) would be:
```yaml
apiVersion: sedna.io/v1alpha1
kind: JointInferenceService
metadata:
  name: example
spec:
  edgeWorker:
    model:
      name: "small-model"
    hardExampleMining:
      name: "IBT"
    template:
      spec:
        nodeName: "edge-node"
        containers:
        - image: edge-inference-worker:latest
          imagePullPolicy: Always
          env:  # user defined environments
          - name: nms_threshold
            value: "0.6"
          ports:  # user defined ports
            - containerPort: 80
              protocol: TCP
          resources:  # user defined resources
            requests:
              memory: 64Mi
              cpu: 100m
            limits:
              memory: 512Mi
          volumeMounts:
            - name: localvideo
              mountPath: /data/
        volumes:   # user defined volumes
          - name: localvideo
            emptyDir: {}
  cloudWorker:
    model:
      name: "big-model"
    template:
      spec:
        nodeName: "cloud-node"
        containers:
          - image: cloud-inference-worker:latest
            imagePullPolicy: Always
            env:  # user defined environments
              - name: nms_threshold
                value: "0.6"
            ports:  # user defined ports
              - containerPort: 80
                protocol: TCP
            resources:  # user defined resources
              limits:
                memory: 2Gi
```
