### ISSUE TITLE
Regarding LocalController Deployment Locations

### ISSUE THREAD

**Issue by ansjin** [kubeedge/sedna#217]
I saw in the installation script of Sedna that LC is deployed as a **DaemonSet** and is allowed to be deployed on every node (cloud-master, cloud-workers, and edge nodes)  (check below). 

**Question:** Does it is required to be run on all cloud-worker nodes or it is only to be run on the cloud-master node? From the sedna architecture diagram (https://github.com/kubeedge/sedna/blob/main/docs/proposals/images/framework.png), **it is shown running on one cloud node (**not the other cloud node**) and on edge nodes. Could you please clarify this?** 

```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    sedna: lc
  name: lc
  namespace: sedna
spec:
  selector:
    matchLabels:
      sedna: lc
  template:
    metadata:
      labels:
        sedna: lc
    spec:
      containers:
        - name: lc
          image: kubeedge/sedna-lc:$SEDNA_VERSION
          env:
            - name: GM_ADDRESS
              value: $GM_ADDRESS
            - name: BIND_PORT
              value: "${SEDNA_LC_BIND_PORT:-9100}"
            - name: NODENAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: ROOTFS_MOUNT_DIR
              # the value of ROOTFS_MOUNT_DIR is same with the mount path of volume
              value: /rootfs
          resources:
            requests:
              memory: 32Mi
              cpu: 100m
            limits:
              memory: 128Mi
          volumeMounts:
            - name: localcontroller
              mountPath: /rootfs
      volumes:
        - name: localcontroller
          hostPath:
            path: /
      restartPolicy: Always
      hostNetwork: true
```
