### ISSUE TITLE
In the lifelong learning atcii classifier demo, inference job error

### ISSUE THREAD

**Issue by hey-kong** [kubeedge/sedna#328]
**What happened**:
inference job error when running lifelong learning atcii classifier demo
<img width="915" alt="Snipaste_2022-06-17_01-08-57" src="https://user-images.githubusercontent.com/54307176/174432892-8b957032-f0e0-4429-8438-24888e1ff0f5.png">
kubectl logs atcii-classifier-demo-inference-sqbjt:
```
/home/lib/sedna/backend/__init__.py:50: UserWarning: SKLEARN Not Support yet, use itself
  warnings.warn(f"{backend_type} Not Support yet, use itself")
Traceback (most recent call last):
  File "inference.py", line 88, in <module>
    print(main())
  File "inference.py", line 75, in main
    rsl, is_unseen, target_task = ll_service.inference(infer_data)
  File "/home/lib/sedna/core/lifelong_learning/lifelong_learning.py", line 365, in inference
    data=data, post_process=post_process, **kwargs
  File "/home/lib/sedna/backend/base.py", line 64, in predict
    return self.estimator.predict(*args, **varkw)
  File "/home/lib/sedna/algorithms/multi_task_learning/multi_task_learning.py", line 375, in predict
    self.load()
  File "/home/lib/sedna/algorithms/multi_task_learning/multi_task_learning.py", line 345, in load
    self.extractor = FileOps.load(self.extractor)
  File "/home/lib/sedna/common/file_ops.py", line 261, in load
    obj = joblib.load(src)
  File "/usr/local/lib/python3.6/site-packages/joblib/numpy_pickle.py", line 585, in load
    obj = _unpickle(fobj, filename, mmap_mode)
  File "/usr/local/lib/python3.6/site-packages/joblib/numpy_pickle.py", line 504, in _unpickle
    obj = unpickler.load()
  File "/usr/local/lib/python3.6/pickle.py", line 1048, in load
    raise EOFError
EOFError
```

**What you expected to happen**:
inference job is in running status

**How to reproduce it (as minimally and precisely as possible)**:
start the lifelong learning job ([Using Lifelong Learning Job in Thermal Comfort Prediction Scenario](https://github.com/kubeedge/sedna/tree/main/examples/lifelong_learning/atcii))

**Anything else we need to know?**:
lifelong learning job yaml:
```
kubectl create -f - <<EOF
apiVersion: sedna.io/v1alpha1
kind: Dataset
metadata:
  name: lifelong-dataset
spec:
  url: "/data/trainData.csv"
  format: "csv"
  nodeName: edge.kubeedge
EOF

kubectl create -f - <<EOF
apiVersion: sedna.io/v1alpha1
kind: LifelongLearningJob
metadata:
  name: atcii-classifier-demo
spec:
  dataset:
    name: "lifelong-dataset"
    trainProb: 0.8
  trainSpec:
    template:
      spec:
        nodeName: edge.kubeedge
        containers:
          - image: kubeedge/sedna-example-lifelong-learning-atcii-classifier:v0.5.0
            name:  train-worker
            imagePullPolicy: IfNotPresent
            args: ["train.py"]  # training script
            env:  # Hyperparameters required for training
              - name: "early_stopping_rounds"
                value: "100"
              - name: "metric_name"
                value: "mlogloss"
    trigger:
      checkPeriodSeconds: 60
      timer:
        start: 00:01
        end: 24:00
      condition:
        operator: ">"
        threshold: 50
        metric: num_of_samples
  evalSpec:
    template:
      spec:
        nodeName: edge.kubeedge
        containers:
          - image: kubeedge/sedna-example-lifelong-learning-atcii-classifier:v0.5.0
            name:  eval-worker
            imagePullPolicy: IfNotPresent
            args: ["eval.py"]
            env:
              - name: "metrics"
                value: "precision_score"
              - name: "metric_param"
                value: "{'average': 'micro'}"
              - name: "model_threshold"  # Threshold for filtering deploy models
                value: "0.5"
  deploySpec:
    template:
      spec:
        nodeName: edge.kubeedge
        containers:
        - image: kubeedge/sedna-example-lifelong-learning-atcii-classifier:v0.5.0
          name:  infer-worker
          imagePullPolicy: IfNotPresent
          args: ["inference.py"]
          env:
          - name: "UT_SAVED_URL"  # unseen tasks save path
            value: "/ut_saved_url"
          - name: "infer_dataset_url"  # simulation of the inference samples
            value: "/data/testData.csv"
          volumeMounts:
          - name: utdir
            mountPath: /ut_saved_url
          - name: inferdata
            mountPath: /data/
          resources:  # user defined resources
            limits:
              memory: 2Gi
        volumes:   # user defined volumes
          - name: utdir
            hostPath:
              path: /lifelong/unseen_task/
              type: DirectoryOrCreate
          - name: inferdata
            hostPath:
              path:  /data/
              type: DirectoryOrCreate
  outputDir: "/output"
EOF
```

**Environment**:
<details><summary>Sedna Version</summary>

```console
v0.5.0
```

</details>

<details><summary>Kubernets Version</summary>

```console
v1.20.0
```

</details>

<details><summary>KubeEdge Version</summary>

```console
v1.9.2
```

</details>

**CloudSide Environment**:
<details><summary>Hardware configuration</summary>

```console
$ lscpu
# paste output here
```

</details>

<details><summary>OS</summary>

```console
$ cat /etc/os-release
# paste output here
```

</details>

<details><summary>Kernel</summary>

```console
$ uname -a
# paste output here
```

</details>

<details><summary>Others</summary>
</details>

**EdgeSide Environment**:
<details><summary>Hardware configuration</summary>

```console
$ lscpu
# paste output here
```

</details>

<details><summary>OS</summary>

```console
$ cat /etc/os-release
# paste output here
```

</details>

<details><summary>Kernel</summary>

```console
$ uname -a
# paste output here
```

</details>

<details><summary>Others</summary>
</details>
