### ISSUE TITLE
Add multi-edge collaborative inference support

### ISSUE THREAD

**Issue by EnfangCui** [kubeedge/sedna#77]
## Motivation
Multi-edge collaborative inference refers to the use of multiple edge computing nodes for collaborative inference. This technology can make full use of the distributed computing resources of edge computing nodes, reduce the delay of edge AI services and improve inference accuracy and throughput. It is a key technology of edge intelligence Therefore, we propose a multi-edge collaborative inference framework to help users build multi-edge collaborative AI business easily based on KubeEdge.

### Goals
* The framework can utilize multiple edge computing nodes for collaborative inference.
* Utilize KubeEdge's EdgeMesh to realize multi-edge load balancing.
* Provide typical multi-edge inference case study (such as ReID, multi-source data fusion, etc.).

### Solution
Take pedestrian ReID as a example:
1.  pedestrian ReID workflow
![image](https://user-images.githubusercontent.com/32125802/120733234-58d2db00-c519-11eb-975a-9e68d04de5d7.png)

The client is used to read the camera video data and carry out the first stage of inference.
The server is used to receive the region proposal predicted by the client for final target detection and pedestrian feature matching.

2. CRD example (preliminary design)
``` yaml
apiVersion: sedna.io/v1alpha1
kind: MultiEdgeInferenceService
metadata:
  name: pedestrian-reid
  namespace: default
spec:
  clientWorkers:
    -template:
      spec:
        containers:
          - image: kubeedge/sedna-example-multi-edge-inference-reid-client:v0.1.0
          ......
        nodeSelector:
          ......
  serverWorkers:
    -template:
      metadata:
      labels:
        app: reid-server
      spec:
        containers:
          - image: kubeedge/sedna-example-multi-edge-inference-reid-server:v0.1.0
          ......
        nodeSelector:
          ......
    -template:
      metadata:
      labels:
        app: user-server
      spec:
        containers:
          - image: kubeedge/sedna-example-multi-edge-inference-user-server:v0.1.0
          ......
        nodeSelector:
          ......
    -template:
      metadata:
      labels:
        app: mqtt-server
      spec:
        containers:
          - image: kubeedge/sedna-example-multi-edge-inference-mqtt-server:v0.1.0
          ......
        nodeSelector:
          ......
```
### Open issues
We hope to build a general framework to adapt to a variety of multi-edge collaborative inference scenarios. Therefore, users and developers are welcome to put forward more scenarios, applications and requirements to improve our architecture and CRD interface design.
